Type emitter
    Field Field0%
    Field Field1#
    Field Field2#
    Field Field3#
    Field Field4.template
    Field Field5%
    Field Field6%
    Field Field7%
    Field Field8%
    Field Field9%
End Type
