Type se_block
    Field Field0%
    Field Field1$
    Field Field2.se_node
    Field Field3.se_token
    Field Field4.se_block
    Field Field5.se_block
    Field Field6.se_block
    Field Field7.se_block
    Field Field8.se_block
End Type
