Type se_functiondef
    Field Field0.se_vf_funcptr
    Field Field1.se_localdef
    Field Field2.se_localdef
    Field Field3.se_staticdef
    Field Field4.se_staticdef
    Field Field5.se_tempvalue
    Field Field6.se_tempvalue
    Field Field7.se_tempvalue
    Field Field8.se_token
End Type
