Type timers
    Field Field0.se_script
    Field Field1.bs
    Field Field2$
    Field Field3%
    Field Field4%
    Field Field5%
    Field Field6.se_funcptr
    Field Field7%
    Field Field8$
End Type
