Type waypoints
    Field Field0%
    Field Field1.doors
    Field Field2.rooms
    Field Field3%
    Field Field4.waypoints[5]
    Field Field5#[5]
    Field Field6#
    Field Field7#
    Field Field8#
    Field Field9.waypoints
End Type
