.lib "blitzsteamworks.dll"

steam_init%():"_Init@0"
steam_restartappifnecessary%(arg0%):"_RestartAppIfNecessary@4"
steam_update%():"_Update@0"
steam_achieve%(arg0$):"_Achieve@4"
steam_setrichpresence%(arg0$, arg1$):"_SetRichPresence@8"
steam_loadsubscribeditems%():"_LoadSubscribedItems@0"
steam_getsubscribeditemcount%():"_GetSubscribedItemCount@0"
steam_getsubscribeditemid$(arg0%):"_GetSubscribedItemID@4"
steam_getsubscribeditempath$(arg0%):"_GetSubscribedItemPath@4"
steam_stringtoidupper%(arg0$):"_StringToIDUpper@4"
steam_stringtoidlower%(arg0$):"_StringToIDLower@4"
steam_idtostring$(arg0%, arg1%):"_IDToString@8"
steam_getplayeridupper%():"_GetPlayerIDUpper@0"
steam_getplayeridlower%():"_GetPlayerIDLower@0"
steam_getplayername$():"_GetPlayerName@0"
steam_pushbyte%(arg0%):"_PushByte@4"
steam_pushshort%(arg0%):"_PushShort@4"
steam_pushint%(arg0%):"_PushInt@4"
steam_pushfloat%(arg0#):"_PushFloat@4"
steam_pushstring%(arg0$):"_PushString@4"
steam_pushbytes%(arg0*, arg1%, arg2%):"_PushBytes@12"
steam_pullbyte%():"_PullByte@0"
steam_pullshort%():"_PullShort@0"
steam_pullint%():"_PullInt@0"
steam_pullfloat%():"_PullFloat@0"
steam_pullstring$():"_PullString@0"
steam_pullbytes%(arg0*, arg1%, arg2%):"_PullBytes@12"
steam_getsenderidupper%():"_GetSenderIDUpper@0"
steam_getsenderidlower%():"_GetSenderIDLower@0"
steam_loadpacket%():"_LoadPacket@0"
steam_sendpackettouser%(arg0%, arg1%, arg2%):"_SendPacketToUser@12"
steam_closeconnection%(arg0%, arg1%):"_CloseConnection@8"
steam_readavail%():"_ReadAvail@0"
steam_createlobby%(arg0%, arg1%):"_CreateLobby@8"
steam_leavelobby%():"_LeaveLobby@0"
steam_setlobbytype%(arg0%):"_SetLobbyType@4"
steam_getlobbystate%():"_GetLobbyState@0"
steam_getlobbyowneridupper%():"_GetLobbyOwnerIDUpper@0"
steam_getlobbyowneridlower%():"_GetLobbyOwnerIDLower@0"
steam_setacceptlobbyinvites%(arg0%):"_SetAcceptLobbyInvites@4"
steam_getauthsessionticket%(arg0*, arg1%):"_GetAuthSessionTicket@8"
steam_cancelauthticket%(arg0%):"_CancelAuthTicket@4"
steam_getauthsessionticketsize%():"_GetAuthSessionTicketSize@0"
steam_getfriendcount%():"_GetFriendCount@0"
steam_getfriendidupper%(arg0%):"_GetFriendIDUpper@4"
steam_getfriendidlower%(arg0%):"_GetFriendIDLower@4"
steam_activateoverlaytouser%(arg0$, arg1%, arg2%):"_ActivateGameOverlayToUser@12"
steam_setplayedwith%(arg0%, arg1%):"_SetPlayedWith@8"
steam_getlargeuseravatar%(arg0%, arg1%):"_GetLargeUserAvatar@8"
steam_getuserimageheight%(arg0%):"_GetUserImageHeight@4"
steam_getuserimagewidth%(arg0%):"_GetUserImageWidth@4"
steam_getuserimagergba%(arg0%, arg1*, arg2%):"_GetUserImageRGBA@12"
steam_requestuserinformation%(arg0%, arg1%, arg2%):"_RequestUserInformation@12"
