.lib "blitzsteam.dll"

bs_helper_copymemoryintmangle%(arg0%, arg1%, arg2%, arg3%, arg4%, arg5%, arg6%, arg7%, arg8%, arg9%, arg10%):"_BS_Helper_CopyMemoryIntMangle@44"
bs_callback_new%(arg0%):"_BS_Callback_New@4"
bs_callback_register%(arg0%, arg1%):"_BS_Callback_Register@8"
bs_callback_registerresult%(arg0%, arg1%, arg2%):"_BS_Callback_RegisterResult@12"
bs_csteamid_new%():"_BS_CSteamID_New@0"
bs_csteamid_copy%(arg0%):"_BS_CSteamID_Copy@4"
bs_csteamid_destroy%(arg0%):"_BS_CSteamID_Destroy@4"
bs_csteamid_new_idinstanceuniversetype%(arg0%, arg1%, arg2%, arg3%):"_BS_CSteamID_New_IdInstanceUniverseType@16"
bs_csteamid_froml%(arg0%):"_BS_CSteamID_FromL@4"
bs_csteamid_set%(arg0%, arg1%, arg2%, arg3%):"_BS_CSteamID_Set@16"
bs_csteamid_islobby%(arg0%):"_BS_CSteamID_IsLobby@4"
bs_csteamid_getaccountid%(arg0%):"_BS_CSteamID_GetAccountID@4"
bs_long_destroy%(arg0%):"_BS_Long_Destroy@4"
bs_long_fromii%(arg0%, arg1%):"_BS_Long_FromII@8"
bs_long_compare%(arg0%, arg1%):"_BS_Long_Compare@8"
bs_memory_peekbyte%(arg0%, arg1%):"_BS_Memory_PeekByte@8"
bs_memory_peekint%(arg0%, arg1%):"_BS_Memory_PeekInt@8"
bs_memory_peekfloat#(arg0%, arg1%):"_BS_Memory_PeekFloat@8"
bs_steamapi_init%():"_BS_SteamAPI_Init@0"
bs_steamapi_runcallbacks%():"_BS_SteamAPI_RunCallbacks@0"
bs_steamclient%():"_BS_SteamClient@0"
bs_isteamclient_setwarningmessagehook%(arg0%, arg1%):"_BS_ISteamClient_SetWarningMessageHook@8"
bs_steamfriends%():"_BS_SteamFriends@0"
bs_isteamfriends_getpersonaname$(arg0%):"_BS_ISteamFriends_GetPersonaName@4"
bs_isteamfriends_getfriendrelationship%(arg0%, arg1%):"_BS_ISteamFriends_GetFriendRelationship@8"
bs_isteamfriends_activategameoverlaytouser%(arg0%, arg1$, arg2%):"_BS_ISteamFriends_ActivateGameOverlayToUser@12"
bs_isteamfriends_setplayedwith%(arg0%, arg1%):"_BS_ISteamFriends_SetPlayedWith@8"
bs_isteamfriends_getlargefriendavatar%(arg0%, arg1%):"_BS_ISteamFriends_GetLargeFriendAvatar@8"
bs_isteamfriends_requestuserinformation%(arg0%, arg1%, arg2%):"_BS_ISteamFriends_RequestUserInformation@12"
bs_isteamfriends_setrichpresence%(arg0%, arg1$, arg2$):"_BS_ISteamFriends_SetRichPresence@12"
bs_steamhtmlsurface%():"_BS_SteamHTMLSurface@0"
bs_isteamhtmlsurface_init%(arg0%):"_BS_ISteamHTMLSurface_Init@4"
bs_isteamhtmlsurface_createbrowser%(arg0%, arg1$, arg2$):"_BS_ISteamHTMLSurface_CreateBrowser@12"
bs_isteamhtmlsurface_removebrowser%(arg0%, arg1%):"_BS_ISteamHTMLSurface_RemoveBrowser@8"
bs_isteamhtmlsurface_loadurl%(arg0%, arg1%, arg2$, arg3$):"_BS_ISteamHTMLSurface_LoadURL@16"
bs_isteamhtmlsurface_setsize%(arg0%, arg1%, arg2%, arg3%):"_BS_ISteamHTMLSurface_SetSize@16"
bs_isteamhtmlsurface_mouseup%(arg0%, arg1%, arg2%):"_BS_ISteamHTMLSurface_MouseUp@12"
bs_isteamhtmlsurface_mousedown%(arg0%, arg1%, arg2%):"_BS_ISteamHTMLSurface_MouseDown@12"
bs_isteamhtmlsurface_mousemove%(arg0%, arg1%, arg2%, arg3%):"_BS_ISteamHTMLSurface_MouseMove@16"
bs_isteamhtmlsurface_allowstartrequest%(arg0%, arg1%, arg2%):"_BS_ISteamHTMLSurface_AllowStartRequest@12"
bs_steammatchmaking%():"_BS_SteamMatchmaking@0"
bs_steammatchmaking_createlobby%(arg0%, arg1%, arg2%):"_BS_ISteamMatchmaking_CreateLobby@12"
bs_steammatchmaking_joinlobby%(arg0%, arg1%):"_BS_ISteamMatchmaking_JoinLobby@8"
bs_steammatchmaking_leavelobby%(arg0%, arg1%):"_BS_ISteamMatchmaking_LeaveLobby@8"
bs_steammatchmaking_setlobbydata%(arg0%, arg1%, arg2$, arg3$):"_BS_ISteamMatchmaking_SetLobbyData@16"
bs_steammatchmaking_getlobbydata$(arg0%, arg1%, arg2$):"_BS_ISteamMatchmaking_GetLobbyData@12"
bs_steammatchmaking_setlobbytype%(arg0%, arg1%, arg2%):"_BS_ISteamMatchmaking_SetLobbyType@12"
bs_steamnetworking%():"_BS_SteamNetworking@0"
bs_isteamnetworking_sendp2ppacket%(arg0%, arg1%, arg2*, arg3%, arg4%, arg5%):"_BS_ISteamNetworking_SendP2PPacket@24"
bs_isteamnetworking_isp2ppacketavailable%(arg0%, arg1*, arg2%):"_BS_ISteamNetworking_IsP2PPacketAvailable@12"
bs_isteamnetworking_readp2ppacket%(arg0%, arg1*, arg2%, arg3*, arg4%, arg5%):"_BS_ISteamNetworking_ReadP2PPacket@24"
bs_isteamnetworking_acceptp2psessionwithuser%(arg0%, arg1%):"_BS_ISteamNetworking_AcceptP2PSessionWithUser@8"
bs_isteamnetworking_closep2psessionwithuser%(arg0%, arg1%):"_BS_ISteamNetworking_CloseP2PSessionWithUser@8"
bs_steamugc%():"_BS_SteamUGC@0"
bs_steamugc_getiteminstallinfo%(arg0%, arg1%, arg2*, arg3*, arg4%, arg5*):"_BS_UGC_GetItemInstallInfo@24"
bs_steamugc_getsubscribeditems%(arg0%):"_BS_UGC_GetSubscribedItems@4"
bs_steamugc_getitemstate%(arg0%, arg1%):"_BS_UGC_GetItemState@8"
bs_steamugc_getnumsubscribeditems%(arg0%):"_BS_UGC_GetNumSubscribedItems@4"
bs_steamugc_downloaditem%(arg0%, arg1%, arg2%):"_BS_UGC_DownloadItem@12"
bs_steamuser%():"_BS_SteamUser@0"
bs_isteamuser_isloggedon%(arg0%):"_BS_ISteamUser_IsLoggedOn@4"
bs_isteamuser_getsteamid%(arg0%):"_BS_ISteamUser_GetSteamID@4"
bs_isteamuser_getauthsessionticket%(arg0%, arg1*, arg2%, arg3*):"_BS_ISteamUser_GetAuthSessionTicket@16"
bs_isteamuser_cancelauthticket%(arg0%, arg1%):"_BS_ISteamUser_CancelAuthTicket@8"
bs_isteamuser_advertisegame%(arg0%, arg1%, arg2%, arg3%):"_BS_ISteamUser_AdvertiseGame@16"
bs_steamuserstats%():"_BS_SteamUserStats@0"
bs_isteamuserstats_requestcurrentstats%(arg0%):"_BS_ISteamUserStats_RequestCurrentStats@4"
bs_isteamuserstats_setachievement%(arg0%, arg1$):"_BS_ISteamUserStats_SetAchievement@8"
bs_isteamuserstats_storestats%(arg0%):"_BS_ISteamUserStats_StoreStats@4"
bs_steamutils%():"_BS_SteamUtils@0"
bs_steamutils_getimagergba%(arg0%, arg1%, arg2*, arg3%):"_BS_SteamUtils_GetImageRGBA@16"
bs_steamutils_getimagesize%(arg0%, arg1%, arg2*, arg3*):"_BS_SteamUtils_GetImageSize@16"
