.lib "user32.dll"

api_closeclipboard%():"CloseClipboard"
api_emptyclipboard%():"EmptyClipboard"
api_getclientrect%(param0%, param1*):"GetClientRect"
api_getclipboarddatatext$(param0%):"GetClipboardData"
api_getdesktopwindow%():"GetDesktopWindow"
api_getforegroundwindow%():"GetForegroundWindow"
api_isclipboardformatavailable%(param0%):"IsClipboardFormatAvailable"
api_openclipboard%(param0%):"OpenClipboard"
api_setclipboarddata%(param0%, param1%):"SetClipboardData"
api_showwindow%(param0%, param1%):"ShowWindow"
