.lib "blitzsteamworks.dll"

steam_stringtoidupper%(arg0$):"_StringToIDUpper@4"
steam_stringtoidlower%(arg0$):"_StringToIDLower@4"
steam_id64to32%(arg0$):"_SteamID64To32@4"
steam_idtostring$(arg0%, arg1%):"_IDToString@8"
steam_getauthsessionresponse%():"__GetAuthSessionResponse@0"
steam_getauthsessionresponseidlower%():"_GetAuthSessionReponseIDLower@0"
steam_getauthsessionresponseidupper%():"_GetAuthSessionReponseIDUpper@0"
gs_init%(arg0%, arg1%, arg2%, arg3%, arg4$):"_GS_Init@20"
gs_geterrormsg$():"_GS_GetErrorMsg@0"
gs_shutdown%():"_GS_Shutdown@0"
gs_logon%(arg0$, arg1$):"_GS_LogOn@8"
gs_logoff%():"_GS_LogOff@0"
gs_isloggedon%():"_GS_IsLoggedOn@0"
gs_update%():"_GS_Update@0"
gs_getsteamserversconnected%():"_GS_GetSteamServersConnected@0"
gs_beginauthsession%(arg0*, arg1%, arg2%, arg3%):"_GS_BeginAuthSession@16"
gs_endauthsession%(arg0%, arg1%):"_GS_EndAuthSession@8"
