Global accesscode%
Global achievementsmenu%
Global achvlocked%
Global achvmsgenabled%
Global allowroomdoorsinit.rooms
Global ambientlightroomtex%
Global ambientsfxchn%
Global apacheobj%
Global apacherotorobj%
Global apachesfx%
Global ark_blur_cam%
Global blinkeffect#
Global blinkeffecttimer#
Global blinkfreq#
Global blinktimer#
Global bloodloss#
Global blurtimer#
Global blurvolume#
Global breachevent.events
Global breachtypesarray.breachtypes[255]
Global breathchn%
Global brightness%
Global bullethitsfx%
Global bumpenabled%
Global burntnote%
Global burstsfx%
Global buttghostsfx%
Global buttoncodeobj%
Global buttonkeyobj%
Global buttonobj%
Global buttonscannerobj%
Global buttonsfx2%
Global cambaseobj%
Global camera%
Global camerafogfar#
Global camerafognear#
Global camerasfx%
Global camerashake#
Global camerashaketimer%
Global camobj%
Global cautionsfx%
Global centralserver.centralserverdata
Global checkfps%
Global classd_model%
Global classdobj%
Global clerkmp%
Global clerkobj%
Global coffincam.securitycams
Global coffindistance#
Global collider%
Global compactbank.bs[1]
Global consoleflush%
Global consoleflushsnd%
Global consolemusflush%
Global consolemusplay%
Global contained106%
Global coughchn%
Global crouch%
Global crouchstate#
Global curr096.npcs
Global curr106.npcs
Global curr173.npcs
Global curr5131.npcs
Global currambientsfx%
Global currcamerazoom#
Global currentdatabasehandle%
Global currentluastate%
Global currentparam%
Global currentplayerinevent%
Global currentstatementhandle%
Global currenttick.ticks
Global currmenu_testimg$
Global currroom2slrendercam%
Global currspeed#
Global currstepsfx%
Global curtime#
Global dark%
Global darktexture%
Global deafplayer%
Global deaftimer#
Global death914sfx%
Global deathmsg$
Global deathtimer%
Global debughud%
Global detectitemmoving%
Global dimension1499.events
Global doorclose079sfx%
Global doorcoll%
Global doorframeobj%
Global doorobj%
Global dooropen079sfx%
Global doubleclick%
Global dropspeed%
Global dsk%
Global dtextures%[11]
Global dynamic_shoot_ticks%
Global elapsedloops%
Global elapsedtime#
Global elevatorbeepsfx%
Global elevatormovesfx%
Global enablevram%
Global endbreathchn%
Global endbreathsfx%
Global endingscreen%
Global endingtimer%
Global errorupd%
Global event173.events
Global exit1event.events
Global explosionsfx%
Global explosiontimer#
Global eyeirritation#
Global eyestuck%
Global fake_stream_ip%
Global falltimer#
Global fasttcp.fasttcps
Global femurbreakersfx%
Global fixedtimesteps%
Global fog%
Global fognvtexture%
Global fogtexture%
Global forceangle%
Global forcemove%
Global forestnpc%
Global forestnpcdata#[3]
Global forestnpctex%
Global fps%
Global fpse%
Global fpsfactor#
Global fpsfactor2#
Global fpsfactorlimit#
Global framelimit%
Global ft.fixedtimesteps
Global gameinfo.g_i
Global gasmaskoverlay%
Global gasmasktexture%
Global gateaevent.events
Global gay%
Global globalmessages%
Global godmode%
Global grabbedentity%
Global grenade_object%
Global guard_model%
Global guard_object%
Global guardobj%
Global gundamage#[16]
Global gunshootticks%[16]
Global gunshot2sfx%
Global gunshot3sfx%
Global gunshotsfx%
Global gunspread#[16]
Global halloweenindex%
Global haos_model%
Global haos_object%
Global hazmat_object%
Global head%
Global headdropspeed%
Global healtimer%
Global heartbeatrate#
Global heartbeatsfx%
Global heartbeattimer%
Global heartbeatvolume#
Global hidedistance#
Global hisssfx%
Global hudenabled%
Global i_zone.mapzones
Global ignorebank%
Global incomingpatron%
Global incomingversion$
Global infacility%
Global infect#
Global infectoverlay%
Global infecttexture%
Global infinitestamina%
Global injuries#
Global insmoke%
Global intercomstreamchn%
Global invertmouse%
Global invokefunctionaddress%
Global isnvgblinking%
Global iszombie%
Global itemsrotaterand%
Global janitor_model%
Global keycardsfx1%
Global keycardsfx2%
Global killanim%
Global killtimer#
Global last_breach_type%
Global lasteventid%
Global lastmousehit1%
Global lastpluginid%
Global leverbaseobj%
Global leverobj%
Global leversfx%
Global light%
Global lightblink#
Global lightconemodel%
Global lightflash#
Global lightsfx%
Global lightson%
Global lighttexture%
Global lightvolume#
Global liquidobj%
Global loopdelay%
Global m_corpse.corpses[256]
Global m_event.events[110]
Global m_item.items[1000]
Global m_npc.npcs[255]
Global machinesfx%
Global magnetdownsfx%
Global magnetupsfx%
Global mainfunction%
Global mainfunctionerror%
Global mainfunctionerrorblock%
Global mainplayer%
Global mapheight%
Global mapwidth%
Global menu_testimg%
Global menuroomscale#
Global menuscale#
Global mesh_magx#
Global mesh_magy#
Global mesh_magz#
Global mesh_maxx#
Global mesh_maxy#
Global mesh_maxz#
Global mesh_minx#
Global mesh_miny#
Global mesh_minz#
Global millisecs_sys%[11]
Global minigun_object%
Global model_035%
Global model_049%
Global model_096%
Global model_106%
Global model_173%
Global model_860%
Global model_939%
Global model_966%
Global model_clerk%
Global model_wait%
Global model_zombie%
Global monitor%
Global monitor2%
Global monitor3%
Global monitortexture%
Global monitortexture2%
Global monitortexture3%
Global monitortexture4%
Global monitortextureoff%
Global monitortimer#
Global monitortimer2#
Global mousedown1%
Global mousehit1%
Global mousehit2%
Global mousesens%
Global mouseup1%
Global movex#
Global movey#
Global movez#
Global mp_door.doors[500]
Global mp_version$
Global mp5_object%
Global mtf_cameracheckdetected%
Global mtf_camerachecktimer#
Global mtfobj%
Global mtfrooms.rooms[10]
Global mtfroomstate%[10]
Global mtftimer#
Global multiplayer_models$[65535]
Global multiplayer_object.mp_objects[255]
Global navbg%
Global network_byte%[7]
Global newyearindex%
Global noclip%
Global noclipspeed#
Global notarget%
Global npc0492obj%
Global npc049obj%
Global npc106obj%
Global npc966obj%
Global ntf_1499prevroom%
Global ntf_1499prevx%
Global ntf_1499prevy%
Global ntf_1499prevz%
Global ntf_1499sky%
Global ntf_1499x%
Global ntf_1499y%
Global ntf_1499z%
Global ntf_model%
Global ntf_object%
Global nuclearsirensfx%
Global nvblink%
Global nvoverlay%
Global nvtexture%
Global nvtimer%
Global obj939%
Global object_096%
Global object_173%
Global opendoorfastsfx%
Global optionsmenu%
Global p90_object%
Global particleamount%
Global particlecam%
Global particleeffect%[10]
Global particlepiv%
Global pistol_object%
Global playable%
Global player.players[65]
Global playerfallingpickdistance#
Global playeroptimize.players[65]
Global playerroom.rooms
Global playersoundvolume#
Global playerzone%
Global playtime%
Global plugins.plugin[64]
Global pocketdimension106.events
Global pointpitch#
Global pointyaw#
Global prevfpsfactor#
Global prevgl$
Global prevmusicvolume%
Global prevsecondarylighton#
Global prevsfxvolume%
Global prevtime#
Global publicreturnedvalue%
Global publics.pb
Global query_global_data%
Global quickload_currevent.events
Global quickloadpercent%
Global quickloadpercent_displaytimer%
Global quitmsg%
Global radiobuzz%
Global radiosquelch%
Global radiostatic%
Global refineditems%
Global regurgitate%
Global remotedooron%
Global restoresanity%
Global retvalmillisecs%
Global rocket_object%
Global room.rooms[200]
Global room2gw_brokendoor%
Global room2gw_x#
Global room2gw_z#
Global room2slcam%
Global room3storageevent.events
Global room860event.events
Global roomambience%[20]
Global roomscale#
Global roomtempid%
Global rpg_object%
Global s_variables.servervariables[512]
Global sanity#
Global save_msg$
Global save_msg_timer%
Global save_msg_y%
Global scannersfx1%
Global scannersfx2%
Global scientist_model%
Global scp1025state#[6]
Global screentexs%[2]
Global script_count%
Global scriptbstream.bs
Global se_arguments_number%
Global se_arguments_stack_level%
Global se_arguments_stack_offset%
Global se_arguments_stack_size%
Global se_current_block%
Global se_current_called_function%
Global se_current_chunk.se_chunk
Global se_current_function.se_funcptr
Global se_current_script.se_script
Global se_current_token.se_token
Global se_error%
Global se_error_dump_line%
Global se_error_message$
Global se_function_def.se_functiondef
Global se_main_function.se_functiondef
Global se_operators$[21]
Global se_order%
Global se_return_value.se_value
Global se_root_block.se_block
Global se_script_access_invoke%
Global se_top_space.se_blockspace
Global se_transient_stack_level%
Global se_transient_stack_offset%
Global se_transient_stack_size%
Global se_vf_func_ptr_n%
Global se_vf_inst_n%
Global se_vf_label_n%
Global se_vf_public_n%
Global se_vf_static_n%
Global secondarylighton#
Global selecteddifficulty.difficulty
Global selectedending$
Global selecteditem%
Global selectedmonitor.securitycams
Global selectedscreen%
Global server.multiplayerserver
Global shake%
Global shouldentitiesfall%
Global shouldrestartserver%
Global shouldstartround%
Global side%
Global sky%
Global smokedelay%
Global soundemitter%
Global soundtransmission%
Global stamina#
Global staminaeffect#
Global staminaeffecttimer#
Global steam_release%
Global stonedragsfx%
Global storedcamerafogfar#
Global superman%
Global supermantimer%
Global surgeon_zombie%
Global templightvolume#
Global tempsoundchn%
Global tempsoundindex%
Global tempsounds%[10]
Global teslaactivatesfx%
Global teslaidlesfx%
Global teslapowerupsfx%
Global teslatexture%
Global ticks.types_ticks
Global triggered096sfx%
Global unabletomove%
Global updatecheckpoint1%
Global updatecheckpoint2%
Global updateroomlightstimer#
Global updateticktime%
Global use914sfx%
Global usedconsole%
Global user_camera_pitch#
Global vomit%
Global vomitchn%
Global vomitsfx%
Global vomittimer#
Global wearing714%
Global wearinggasmask%
Global wearinghazmat%
Global wearingnightvision%
Global wearingvest%
Global worker_model%
