Function checkoptionsini%()
    If (((filetype("options.ini") = $01) And (filesize("options.ini") > $00)) <> 0) Then
        Return $00
    EndIf
    createfile("options.ini")
    putinivalue("options.ini", "options", "framelimit", (Str framelimit))
    putinivalue("options.ini", "options", "show FPS", "1")
    putinivalue("options.ini", "options", "vsync", "0")
    putinivalue("options.ini", "options", "borderless windowed", "1")
    putinivalue("options.ini", "options", "16bit", "0")
    putinivalue("options.ini", "options", "discord rich presence", "1")
    putinivalue("options.ini", "options", "antialias", "0")
    putinivalue("options.ini", "options", "gammaoff", "0")
    putinivalue("options.ini", "options", "screengamma", "0.0")
    putinivalue("options.ini", "options", "enable vram", "0")
    putinivalue("options.ini", "options", "bump mapping enabled", "0")
    putinivalue("options.ini", "options", "texture details", "2")
    putinivalue("options.ini", "options", "removeparticles", "0")
    putinivalue("options.ini", "options", "particle amount", "2")
    putinivalue("options.ini", "options", "removedecals", "0")
    putinivalue("options.ini", "options", "room lights enabled", "1")
    putinivalue("options.ini", "options", "camera fog near", "0.5")
    putinivalue("options.ini", "options", "camera fog far", "6.0")
    putinivalue("options.ini", "options", "cameraupd", "2")
    putinivalue("options.ini", "options", "cameraquality", "2")
    putinivalue("options.ini", "options", "fov", "75.0")
    putinivalue("options.ini", "options", "HUD enabled", "1")
    putinivalue("options.ini", "options", "Overlays enabled", "1")
    putinivalue("options.ini", "options", "enablebullets", "1")
    putinivalue("options.ini", "options", "showscpviewmodel", "1")
    putinivalue("options.ini", "options", "play startup video", "1")
    putinivalue("options.ini", "options", "achievement popup enabled", "1")
    putinivalue("options.ini", "console", "enabled", "0")
    putinivalue("options.ini", "console", "auto opening", "0")
    putinivalue("options.ini", "options", "mouse sensitivity", "0.0")
    putinivalue("options.ini", "options", "mouse smoothing", "0.0")
    putinivalue("options.ini", "options", "raw mouse input", "0")
    putinivalue("options.ini", "options", "invert mouse y", "0")
    putinivalue("options.ini", "binds", "Up key", "17")
    putinivalue("options.ini", "binds", "Down key", "31")
    putinivalue("options.ini", "binds", "Left key", "30")
    putinivalue("options.ini", "binds", "Right key", "32")
    putinivalue("options.ini", "binds", "Sprint key", "42")
    putinivalue("options.ini", "binds", "Crouch key", "29")
    putinivalue("options.ini", "binds", "Jump key", "57")
    putinivalue("options.ini", "binds", "LeanL key", "16")
    putinivalue("options.ini", "binds", "LeanR key", "18")
    putinivalue("options.ini", "binds", "Blink key", "48")
    putinivalue("options.ini", "binds", "Inventory key", "15")
    putinivalue("options.ini", "binds", "Voice key", "47")
    putinivalue("options.ini", "binds", "Chat key", "20")
    putinivalue("options.ini", "binds", "Save key", "63")
    putinivalue("options.ini", "binds", "Console key", "61")
    putinivalue("options.ini", "binds", "mouseinteract", "1")
    putinivalue("options.ini", "binds", "Using key", "33")
    putinivalue("options.ini", "audio", "music volume", "0.5")
    putinivalue("options.ini", "audio", "sound volume", "0.5")
    putinivalue("options.ini", "audio", "sfx release", "1")
    putinivalue("options.ini", "audio", "enable user tracks", "1")
    putinivalue("options.ini", "audio", "user track setting", "1")
    putinivalue("options.ini", "launcher", "launcher enabled", "1")
    Return $00
End Function
