Function initmultiplayerimages%()
    Local local0#
    Local local1#
    Local local2#
    local0 = menuscale
    local1 = (0.6 * local0)
    local2 = (local0 * (1.0 / 1.16))
    mpimg\Field2[$00] = loadimage_strict("GFX\multiplayer\game\images\sound.png")
    mpimg\Field2[$01] = loadimage_strict("GFX\multiplayer\game\images\radiosound.png")
    mpimg\Field0 = loadimage_strict("GFX\multiplayer\game\images\va.png")
    mpimg\Field1 = loadimage_strict("GFX\multiplayer\game\images\vt.png")
    mpimg\Field4 = loadimage_strict("GFX\multiplayer\menu\voice.png")
    mpimg\Field3 = loadimage_strict("GFX\multiplayer\menu\nocheat.png")
    mpimg\Field8 = loadimage_strict("GFX\multiplayer\menu\lock.png")
    mpimg\Field9 = loadimage_strict("GFX\multiplayer\menu\lockr.png")
    mpimg\Field5[$00] = loadimage_strict("GFX\multiplayer\menu\p1.png")
    mpimg\Field5[$01] = loadimage_strict("GFX\multiplayer\menu\p0.png")
    mpimg\Field6[$01] = loadimage_strict("GFX\menu\arrow.png")
    mpimg\Field7 = loadanimimage("GFX\multiplayer\menu\load.png", $276, $27D, $00, $0B)
    mpimg\Field10 = loadimage_strict("GFX\multiplayer\game\images\smile2.jpg")
    mpimg\Field11 = loadimage_strict("GFX\multiplayer\game\images\smile.jpg")
    mpimg\Field12 = loadimage_strict("GFX\multiplayer\game\images\friend10x10.png")
    mpimg\Field6[$00] = copyimage(mpimg\Field6[$01])
    rotateimage(mpimg\Field6[$00], 180.0)
    handleimage(mpimg\Field6[$00], $00, $00)
    resizeimage(mpimg\Field2[$00], (Float imenuscale[$10]), (Float imenuscale[$10]))
    resizeimage(mpimg\Field2[$01], (Float imenuscale[$10]), (Float imenuscale[$10]))
    resizeimage(mpimg\Field0, (Float imenuscale[$32]), (Float imenuscale[$32]))
    resizeimage(mpimg\Field1, (Float imenuscale[$32]), (Float imenuscale[$32]))
    resizeimage(mpimg\Field5[$00], ((Float imagewidth(mpimg\Field5[$00])) * local0), ((Float imageheight(mpimg\Field5[$00])) * local0))
    resizeimage(mpimg\Field5[$01], ((Float imagewidth(mpimg\Field5[$01])) * local0), ((Float imageheight(mpimg\Field5[$01])) * local0))
    resizeimage(mpimg\Field6[$00], ((Float imagewidth(mpimg\Field6[$00])) * local1), ((Float imageheight(mpimg\Field6[$00])) * local1))
    resizeimage(mpimg\Field6[$01], ((Float imagewidth(mpimg\Field6[$01])) * local1), ((Float imageheight(mpimg\Field6[$01])) * local1))
    resizeimage(mpimg\Field3, (Float imenuscale[$0A]), (Float imenuscale[$0B]))
    resizeimage(mpimg\Field4, (Float imenuscale[$0A]), (Float imenuscale[$0D]))
    resizeimage(mpimg\Field8, (Float imenuscale[$0F]), (Float imenuscale[$0F]))
    resizeimage(mpimg\Field9, (Float imenuscale[$0F]), (Float imenuscale[$0F]))
    resizeimage(mpimg\Field7, (Float imenuscale[$1E]), (Float imenuscale[$1E]))
    resizeimage(mpimg\Field10, (Float imenuscale[$14]), (Float imenuscale[$14]))
    resizeimage(mpimg\Field11, (Float imenuscale[$14]), (Float imenuscale[$14]))
    resizeimage(mpimg\Field12, (Float imenuscale[$0A]), (Float imenuscale[$0A]))
    maskimage(mpimg\Field1, $00, $00, $00)
    maskimage(mpimg\Field0, $00, $00, $00)
    maskimage(mpimg\Field3, $00, $00, $00)
    maskimage(mpimg\Field4, $00, $00, $00)
    maskimage(mpimg\Field10, $00, $00, $00)
    maskimage(mpimg\Field11, $00, $00, $00)
    maskimage(mpimg\Field12, $00, $00, $00)
    Return $00
End Function
