Function isanotremovedevent%(arg0.events)
    Select arg0\Field22
        Case $3F,$3B,$28
            Return $01
        Case $37
            Return $01
        Case $36
            Return $01
        Case $0E
            Return $01
        Case $4A
            Return $01
        Case $02
            Return $01
        Case $39
            Return $01
        Case $3E
            Return $01
        Case $2D
            Return $01
        Case $1E
            Return $01
        Case $33
            Return $01
    End Select
    Return $00
    Return $00
End Function
