Function saveoptionsini%()
    putinivalue("options.ini", "options", "framelimit", (Str framelimit))
    putinivalue("options.ini", "options", "show FPS", (Str showfps))
    putinivalue("options.ini", "options", "vsync", (Str verticalsync))
    putinivalue("options.ini", "options", "antialias", (Str opt_antialias))
    putinivalue("options.ini", "options", "gammaoff", (Str turnongamma))
    putinivalue("options.ini", "options", "screengamma", (Str screengamma))
    putinivalue("options.ini", "options", "enable vram", (Str enablevram))
    putinivalue("options.ini", "options", "bump mapping enabled", (Str bumpenabled))
    putinivalue("options.ini", "options", "removeparticles", (Str removeparticles))
    putinivalue("options.ini", "options", "particle amount", (Str particleamount))
    putinivalue("options.ini", "options", "removedecals", (Str removedecals))
    putinivalue("options.ini", "options", "room lights enabled", (Str enableroomlights))
    putinivalue("options.ini", "options", "cameraupd", (Str camupdate))
    putinivalue("options.ini", "options", "cameraquality", (Str camquality))
    putinivalue("options.ini", "options", "fov", (Str mainfov))
    putinivalue("options.ini", "options", "HUD enabled", (Str hudenabled))
    putinivalue("options.ini", "options", "Overlays enabled", (Str overlaysenabled))
    putinivalue("options.ini", "options", "enablebullets", (Str enablebullets))
    putinivalue("options.ini", "options", "showscpviewmodel", (Str showscpviewmodel))
    putinivalue("options.ini", "options", "achievement popup enabled", (Str achvmsgenabled))
    putinivalue("options.ini", "console", "enabled", (Str canopenconsole))
    putinivalue("options.ini", "console", "auto opening", (Str consoleopening))
    putinivalue("options.ini", "options", "mouse sensitivity", (Str mousesens))
    putinivalue("options.ini", "options", "mouse smoothing", (Str mousesmooth))
    putinivalue("options.ini", "options", "raw mouse input", (Str rawmouseinput))
    putinivalue("options.ini", "options", "invert mouse y", (Str invertmouse))
    putinivalue("options.ini", "binds", "Up key", (Str key_up))
    putinivalue("options.ini", "binds", "Down key", (Str key_down))
    putinivalue("options.ini", "binds", "Left key", (Str key_left))
    putinivalue("options.ini", "binds", "Right key", (Str key_right))
    putinivalue("options.ini", "binds", "Sprint key", (Str key_sprint))
    putinivalue("options.ini", "binds", "Crouch key", (Str key_crouch))
    putinivalue("options.ini", "binds", "Jump key", (Str key_jump))
    putinivalue("options.ini", "binds", "LeanL key", (Str key_leanl))
    putinivalue("options.ini", "binds", "LeanR key", (Str key_leanr))
    putinivalue("options.ini", "binds", "Blink key", (Str key_blink))
    putinivalue("options.ini", "binds", "Inventory key", (Str key_inv))
    putinivalue("options.ini", "binds", "Voice key", (Str key_voice))
    putinivalue("options.ini", "binds", "Chat key", (Str key_chat))
    putinivalue("options.ini", "binds", "Save key", (Str key_save))
    putinivalue("options.ini", "binds", "Console key", (Str key_console))
    putinivalue("options.ini", "binds", "mouseinteract", (Str mouseinteract))
    putinivalue("options.ini", "binds", "Using key", (Str key_using))
    putinivalue("options.ini", "audio", "music volume", (Str musicvolume))
    putinivalue("options.ini", "audio", "sound volume", (Str sfxvolume))
    putinivalue("options.ini", "audio", "sfx release", (Str enablesfxrelease))
    putinivalue("options.ini", "audio", "enable user tracks", (Str enableusertracks))
    putinivalue("options.ini", "audio", "user track setting", (Str usertrackmode))
    Return $00
End Function
