Function savemultiplayeroptions%()
    putinivalue("options.ini", "multiplayer", "voice volume", (Str (voice\Field6 * 100.0)))
    putinivalue("options.ini", "multiplayer", "player volume", (Str (mainplayersvolume * 100.0)))
    putinivalue("options.ini", "multiplayer", "push To talk", (Str voice\Field14))
    putinivalue("options.ini", "multiplayer", "download speed", (Str (Int networkserver\Field31)))
    putinivalue("options.ini", "multiplayer", "nickname", nickname)
    putinivalue("options.ini", "multiplayer", "see names", (Str networkserver\Field52\Field11))
    putinivalue("options.ini", "chat", "graphic width", (Str graphicwidth))
    putinivalue("options.ini", "chat", "graphic height", (Str graphicheight))
    putinivalue("options.ini", "chat", "x", (Str chatoffsetx))
    putinivalue("options.ini", "chat", "y", (Str chatoffsety))
    putinivalue("options.ini", "chat", "width", (Str chatwidth))
    putinivalue("options.ini", "chat", "height", (Str chatheight))
    Return $00
End Function
