Function voice_file_addwavheader%(arg0%, arg1%)
    writeint(arg0, tobytes("RIFF"))
    writeint(arg0, (arg1 + $24))
    writeint(arg0, tobytes("WAVE"))
    writeint(arg0, tobytes("fmt "))
    writeint(arg0, $10)
    writeshort(arg0, $01)
    writeshort(arg0, $01)
    writeint(arg0, voice\Field5)
    writeint(arg0, (voice\Field5 Shl $01))
    writeshort(arg0, $02)
    writeshort(arg0, $10)
    writeint(arg0, tobytes("data"))
    writeint(arg0, arg1)
    Return $00
End Function
