Type drawportal
    Field Field0#
    Field Field1#
    Field Field2%
    Field Field3%
    Field Field4#
    Field Field5#
    Field Field6#
    Field Field7#
    Field Field8%
    Field Field9%
    Field Field10%
    Field Field11%
End Type
