Type emitter
    Field Field0#
    Field Field1#
    Field Field2#
    Field Field3.template
    Field Field4%
    Field Field5%
    Field Field6%
    Field Field7%
    Field Field8%
    Field Field9%
    Field Field10.rooms
    Field Field11%
    Field Field12%
    Field Field13#
End Type
