Type mp_playercorpse
    Field Field0%
    Field Field1%
    Field Field2%
    Field Field3%
    Field Field4%
    Field Field5%
    Field Field6.items[10]
    Field Field7.mp_attachmodel[10]
    Field Field8%[10]
    Field Field9%
    Field Field10#
    Field Field11%
    Field Field12%
    Field Field13%
    Field Field14%
    Field Field15%
    Field Field16%
    Field Field17#
End Type
