Type multiplayerimages
    Field Field0%
    Field Field1%
    Field Field2%[1]
    Field Field3%
    Field Field4%
    Field Field5%[2]
    Field Field6%[2]
    Field Field7%
    Field Field8%
    Field Field9%
    Field Field10%
    Field Field11%
    Field Field12%
End Type
