Type multiplayerimages
    Field Field0%
    Field Field1%
    Field Field2%
    Field Field3%
    Field Field4%
    Field Field5%
    Field Field6%
    Field Field7%[2]
    Field Field8%[2]
    Field Field9%
    Field Field10%
    Field Field11%
    Field Field12%
    Field Field13%
    Field Field14%
End Type
