Type queuedsubtitlesmsg
    Field Field0$
    Field Field1.subtitlesmsg
    Field Field2.sound
    Field Field3$
    Field Field4%
    Field Field5%
    Field Field6%
    Field Field7#
    Field Field8#
End Type
