Type rooms
    Field Field0%
    Field Field1%
    Field Field2%
    Field Field3#
    Field Field4#
    Field Field5#
    Field Field6%
    Field Field7.roomtemplates
    Field Field8#
    Field Field9%
    Field Field10.forest
    Field Field11%[30]
    Field Field12%[30]
    Field Field13.levers[4]
    Field Field14.doors[8]
    Field Field15.npcs[12]
    Field Field16.securitycams[8]
    Field Field17.emitter[8]
    Field Field18.mtgrid
    Field Field19.rooms[4]
    Field Field20.doors[4]
    Field Field21%[3]
    Field Field22#
    Field Field23#
    Field Field24#
    Field Field25#
    Field Field26#
    Field Field27#
    Field Field28#
    Field Field29%
    Field Field30%
    Field Field31%
    Field Field32.mp_roomobject[30]
    Field Field33.mp_roomlever[4]
End Type
