Type se_node
    Field Field0.se_token
    Field Field1%
    Field Field2%
    Field Field3%
    Field Field4.se_node[2]
    Field Field5.se_node[2]
    Field Field6.se_node
    Field Field7.se_node
    Field Field8.se_node
End Type
