Type se_value
    Field Field0%
    Field Field1%
    Field Field2#
    Field Field3$
    Field Field4.se_value
    Field Field5.se_array
    Field Field6.se_inst
    Field Field7.se_funcptr
    Field Field8%
End Type
