Type securitycams
    Field Field0%
    Field Field1%
    Field Field2%
    Field Field3%
    Field Field4%
    Field Field5%
    Field Field6%
    Field Field7%
    Field Field8#
    Field Field9#
    Field Field10#
    Field Field11#
    Field Field12%
    Field Field13%
    Field Field14%
    Field Field15#
    Field Field16.rooms
    Field Field17%
    Field Field18%
    Field Field19%
    Field Field20%
    Field Field21%
    Field Field22%
End Type
