Type template
    Field Field0.template[7]
    Field Field1%
    Field Field2%
    Field Field3%
    Field Field4%
    Field Field5%
    Field Field6%
    Field Field7%
    Field Field8%
    Field Field9%
    Field Field10#
    Field Field11%
    Field Field12#
    Field Field13#
    Field Field14#
    Field Field15#
    Field Field16#
    Field Field17#
    Field Field18#
    Field Field19#
    Field Field20#
    Field Field21#
    Field Field22#
    Field Field23#
    Field Field24#
    Field Field25#
    Field Field26#
    Field Field27%
    Field Field28%
    Field Field29#
    Field Field30#
    Field Field31%
    Field Field32#
    Field Field33#
    Field Field34#
    Field Field35#
    Field Field36#
    Field Field37#
    Field Field38%
    Field Field39%
    Field Field40%
    Field Field41%
    Field Field42%
    Field Field43%
    Field Field44%
    Field Field45#
    Field Field46#
    Field Field47%
    Field Field48%
    Field Field49#
End Type
