Type tgg_textline
    Field Field0%
    Field Field1$
    Field Field2%[250]
    Field Field3%[250]
    Field Field4.tgg_font
    Field Field5%
    Field Field6#
    Field Field7%
    Field Field8%
    Field Field9#
    Field Field10%
    Field Field11%
End Type
