Function sendserverdatatoplayer%(arg0%, arg1%)
    udp_writebyte($1A)
    udp_writebyte($00)
    udp_writeline(server\Field7)
    udp_writebyte(server\Field8)
    udp_writebyte(server\Field2)
    udp_writebyte(server\Field10)
    udp_writefloat(server\Field15)
    udp_writeint(server\Field13)
    udp_writefloat(server\Field20)
    udp_writebyte(server\Field19)
    udp_writebyte(server\Field18)
    udp_writebyte(server\Field3)
    udp_writebyte(server\Field21)
    udp_writebyte(server\Field31)
    udp_writebyte($00)
    udp_writeint((gameinfo\Field5\Field1 - millisecs()))
    udp_writeint(server\Field22)
    udp_writebyte($00)
    udp_writeint((gameinfo\Field5\Field2 - millisecs()))
    udp_writebyte($00)
    udp_writebyte(server\Field9)
    udp_writeint(server\Field32)
    udp_writeline(strippath(server\Field46))
    udp_writebyte($00)
    udp_writebyte(server\Field51)
    udp_writebyte(server\Field56)
    udp_writebyte(server\Field58)
    udp_writebyte(server\Field59)
    udp_writebyte(server\Field63)
    udp_writeline(server\Field73)
    udp_writeline(server\Field74)
    udp_writebyte(halloweenindex)
    udp_writebyte(newyearindex)
    sendudpmsg(server\Field0, arg0, arg1)
    Return $00
End Function
