Function updateservermain%()
    updaterooms()
    updatenpcs()
    mp_updateplayers($00)
    updateemitters()
    updatedoors()
    updateparticles()
    updatedevilemitters()
    updateparticles_devil()
    updatedecals()
    updatemtf()
    updaterockets()
    updatesecuritycams()
    updateitems()
    updatedeadbodies()
    updateworld(1.0)
    quickloadevents()
    updateevents()
    updatedimension1499()
    Return $00
End Function
